// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjhpxrfyitpiqtwaeeal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqaHB4cmZ5aXRwaXF0d2FlZWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzgzODgsImV4cCI6MjA3MjExNDM4OH0.ke_THT8Pan-fcHM3AtEi76Qj81VFUh-d2s9ybTll7K8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});